chore: add schema option
SoftwareBrothers/adminjs-sql pull request #4
Opened 2023-04-20 12:57 UTC by matex1024

2023-04-20 13:21 UTC, dziraf requested changes
@matex1024 looks like build is failing in CI

2023-04-20 13:21 UTC, dziraf commented on src/dialects/base-database.parser.ts
> +    throw new Error('Implement "getSchema" method for your database parser!');
`getSchema` or `getSchemas`?

2023-04-20 13:21 UTC, dziraf commented on src/dialects/postgres.parser.ts
> +    const schemaName = await this.getSchemas();
`'schemaName' is assigned a value but never used`

2023-04-20 13:21 UTC, dziraf commented on src/dialects/postgres.parser.ts
> +  public async getTables(schema = 'public') {
why `schema` arg, shouldn't it just use `this.schemaName`?

2023-05-04 12:40 UTC, devjiwonchoi commented
Hi, I'm the one who brought up this issue and realized that it hasn't been resolved. Regardless of the steps of contribution, if you all don't mind may I participate to solve this issue?

2023-05-24 12:26 UTC, closed without merging